version: '3.8'

services:
  api:
    build: .
    ports:
      - 8004:8000
    command: uvicorn "app.main:app" --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery --workdir=. worker --loglevel=info -P solo
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 
    depends_on:
      - api
      - redis

  redis:
    image: redis:7
